#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
单端微带线建模脚本生成器
完全基于 tline_1.py 录制的完整单条微带线脚本
"""

import os
from datetime import datetime
from typing import Dict, Any, Optional


class TLineScriptBuilder:
    """单端微带线 HFSS 脚本生成器 - 完全基于 tline_1.py"""

    def __init__(self,
                 project_name: str = "tlin1",
                 design_name: str = "HFSSDesign1",
                 target_freq: float = 5.0,
                 material: str = "FR4_epoxy",
                 conductor: str = "copper"):
        self.project_name = project_name
        self.design_name = design_name
        self.target_freq = target_freq
        self.material = material
        self.conductor = conductor

        # 基础参数 - 与 tline_1.py 完全一致
        self.params = {
            "W0": 40.0,      # 地平面宽度
            "L0": 100.0,     # 地平面长度 (同时也是信号线长度 l1)
            "w1": 2.85,      # 信号线宽度
            "l1": 100.0,     # 信号线长度 (= L0)
            "H": 1.6,        # 介质厚度
        }

        self.line = {
            "name": "TL0",
            "w": 2.85,
            "l": 100.0,
            "port_impedance": 50.0,
        }

        self.script_lines = []
        self._header_added = False
        self._variables_added = False
        self._substrate_added = False
        self._signal_line_added = False
        self._ground_added = False
        self._ports_added = False
        self._boundary_added = False
        self._setup_added = False
        self._reports_added = False
        self._analyze_added = False
        self._save_added = False

    def set_line(self, w: float = 2.85, l: float = 100.0,
                 name: str = "TL0", port_impedance: float = 50.0):
        """设置微带线参数"""
        self.line["w"] = w
        self.line["l"] = l
        self.line["name"] = name
        self.line["port_impedance"] = port_impedance
        # 更新参数：w1 和 l1 同时更新
        self.params["w1"] = w
        self.params["l1"] = l
        # l1 必须等于 L0
        self.params["L0"] = l
        return self

    def set_common_params(self, **kwargs):
        """设置通用参数"""
        for key, value in kwargs.items():
            if key in self.params:
                self.params[key] = value
        # 确保 l1 = L0
        self.params["l1"] = self.params["L0"]
        return self

    def _add_line(self, text: str):
        self.script_lines.append(text)

    def add_header(self):
        if self._header_added:
            return self

        header = f'''# ----------------------------------------------
# Script Generated by WHYAVE-AI TLine Builder
# Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
# TLine Type: Single Microstrip Line
# Target Frequency: {self.target_freq} GHz
# ----------------------------------------------
import ScriptEnv
ScriptEnv.Initialize("Ansoft.ElectronicsDesktop")
oDesktop.RestoreWindow()
oProject = oDesktop.NewProject()
oProject.InsertDesign("HFSS", "{self.design_name}", "DrivenModal", "")
oDesign = oProject.SetActiveDesign("{self.design_name}")
oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers", 
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:W0",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "{self.params['W0']}mm"
				],
				[
					"NAME:L0",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "{self.params['L0']}mm"
				],
				[
					"NAME:w1",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "{self.params['w1']}mm"
				],
				[
					"NAME:l1",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "{self.params['l1']}mm"
				],
				[
					"NAME:H",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "{self.params['H']}mm"
				]
			]
		]
	])
oEditor = oDesign.SetActiveEditor("3D Modeler")
'''
        self._add_line(header)
        self._header_added = True
        return self

    def add_substrate(self):
        """添加介质基板 - 与 tline_1.py 完全一致"""
        if self._substrate_added:
            return self

        self._add_line('# ============================================')
        self._add_line('# Substrate')
        self._add_line('# ============================================')
        self._add_line('oEditor.CreateBox(')
        self._add_line('	[')
        self._add_line('		"NAME:BoxParameters",')
        self._add_line('		"XPosition:="		, "-0.8mm",')
        self._add_line('		"YPosition:="		, "-0.9mm",')
        self._add_line('		"ZPosition:="		, "0mm",')
        self._add_line('		"XSize:="		, "1.6mm",')
        self._add_line('		"YSize:="		, "2.1mm",')
        self._add_line('		"ZSize:="		, "0.3mm"')
        self._add_line('	],')
        self._add_line('	[')
        self._add_line('		"NAME:Attributes",')
        self._add_line('		"Name:="		, "Box1",')
        self._add_line('		"Flags:="		, "",')
        self._add_line('		"Color:="		, "(143 175 143)",')
        self._add_line('		"Transparency:="	, 0,')
        self._add_line('		"PartCoordinateSystem:=", "Global",')
        self._add_line('		"UDMId:="		, "",')
        self._add_line('		"MaterialValue:="	, "\\"vacuum\\"",')
        self._add_line('		"SurfaceMaterialValue:=", "\\"\\"",')
        self._add_line('		"SolveInside:="		, True,')
        self._add_line('		"ShellElement:="	, False,')
        self._add_line('		"ShellElementThickness:=", "0mm",')
        self._add_line('		"IsMaterialEditable:="	, True,')
        self._add_line('		"UseMaterialAppearance:=", False,')
        self._add_line('		"IsLightweight:="	, False')
        self._add_line('	])')

        # 修改位置/尺寸
        self._add_line('oEditor.ChangeProperty(')
        self._add_line('	[')
        self._add_line('		"NAME:AllTabs",')
        self._add_line('		[')
        self._add_line('			"NAME:Geometry3DCmdTab",')
        self._add_line('			[')
        self._add_line('				"NAME:PropServers",')
        self._add_line('				"Box1:CreateBox:1"')
        self._add_line('			],')
        self._add_line('			[')
        self._add_line('				"NAME:ChangedProps",')
        self._add_line('				[')
        self._add_line('					"NAME:Position",')
        self._add_line('					"X:="			, "-W0/2",')
        self._add_line('					"Y:="			, "-L0/2",')
        self._add_line('					"Z:="			, "0mm"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:XSize",')
        self._add_line('					"Value:="		, "W0"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:YSize",')
        self._add_line('					"Value:="		, "L0"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:ZSize",')
        self._add_line('					"Value:="		, "-H"')
        self._add_line('				]')
        self._add_line('			]')
        self._add_line('		]')
        self._add_line('	])')

        # 修改属性 (名称/材料/透明度)
        self._add_line('oEditor.ChangeProperty(')
        self._add_line('	[')
        self._add_line('		"NAME:AllTabs",')
        self._add_line('		[')
        self._add_line('			"NAME:Geometry3DAttributeTab",')
        self._add_line('			[')
        self._add_line('				"NAME:PropServers",')
        self._add_line('				"Box1"')
        self._add_line('			],')
        self._add_line('			[')
        self._add_line('				"NAME:ChangedProps",')
        self._add_line('				[')
        self._add_line('					"NAME:Name",')
        self._add_line('					"Value:="		, "Sub"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:Material",')
        self._add_line(f'					"Value:="		, "\\"{self.material}\\""')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:Transparent",')
        self._add_line('					"Value:="		, 0.8')
        self._add_line('				]')
        self._add_line('			]')
        self._add_line('		]')
        self._add_line('	])')
        self._add_line('')

        self._substrate_added = True
        return self

    def add_signal_line(self):
        """添加信号线 TL0 - 与 tline_1.py 完全一致"""
        if self._signal_line_added:
            return self

        w = self.line["w"]
        l = self.line["l"]

        self._add_line('# ============================================')
        self._add_line('# Signal Line TL0')
        self._add_line('# ============================================')
        self._add_line('oEditor.CreateBox(')
        self._add_line('	[')
        self._add_line('		"NAME:BoxParameters",')
        self._add_line('		"XPosition:="		, "-5mm",')
        self._add_line('		"YPosition:="		, "-45mm",')
        self._add_line('		"ZPosition:="		, "0mm",')
        self._add_line('		"XSize:="		, "5mm",')
        self._add_line('		"YSize:="		, "90mm",')
        self._add_line('		"ZSize:="		, "5mm"')
        self._add_line('	],')
        self._add_line('	[')
        self._add_line('		"NAME:Attributes",')
        self._add_line('		"Name:="		, "Box1",')
        self._add_line('		"Flags:="		, "",')
        self._add_line('		"Color:="		, "(143 175 143)",')
        self._add_line('		"Transparency:="	, 0,')
        self._add_line('		"PartCoordinateSystem:=", "Global",')
        self._add_line('		"UDMId:="		, "",')
        self._add_line('		"MaterialValue:="	, "\\"vacuum\\"",')
        self._add_line('		"SurfaceMaterialValue:=", "\\"\\"",')
        self._add_line('		"SolveInside:="		, True,')
        self._add_line('		"ShellElement:="	, False,')
        self._add_line('		"ShellElementThickness:=", "0mm",')
        self._add_line('		"IsMaterialEditable:="	, True,')
        self._add_line('		"UseMaterialAppearance:=", False,')
        self._add_line('		"IsLightweight:="	, False')
        self._add_line('	])')

        # 修改位置/尺寸 - 使用 w1 和 l1 变量
        self._add_line('oEditor.ChangeProperty(')
        self._add_line('	[')
        self._add_line('		"NAME:AllTabs",')
        self._add_line('		[')
        self._add_line('			"NAME:Geometry3DCmdTab",')
        self._add_line('			[')
        self._add_line('				"NAME:PropServers",')
        self._add_line('				"Box1:CreateBox:1"')
        self._add_line('			],')
        self._add_line('			[')
        self._add_line('				"NAME:ChangedProps",')
        self._add_line('				[')
        self._add_line('					"NAME:Position",')
        self._add_line('					"X:="			, "-w1/2",')
        self._add_line('					"Y:="			, "-l1/2",')
        self._add_line('					"Z:="			, "0mm"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:XSize",')
        self._add_line('					"Value:="		, "w1"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:YSize",')
        self._add_line('					"Value:="		, "l1"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:ZSize",')
        self._add_line('					"Value:="		, "0.035mm"')
        self._add_line('				]')
        self._add_line('			]')
        self._add_line('		]')
        self._add_line('	])')

        # 修改属性 (名称/材料/透明度/颜色)
        self._add_line('oEditor.ChangeProperty(')
        self._add_line('	[')
        self._add_line('		"NAME:AllTabs",')
        self._add_line('		[')
        self._add_line('			"NAME:Geometry3DAttributeTab",')
        self._add_line('			[')
        self._add_line('				"NAME:PropServers",')
        self._add_line('				"Box1"')
        self._add_line('			],')
        self._add_line('			[')
        self._add_line('				"NAME:ChangedProps",')
        self._add_line('				[')
        self._add_line('					"NAME:Name",')
        self._add_line(f'					"Value:="		, "{self.line["name"]}"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:Material",')
        self._add_line(f'					"Value:="		, "\\"{self.conductor}\\""')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:Transparent",')
        self._add_line('					"Value:="		, 0.8')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:Color",')
        self._add_line('					"R:="			, 255,')
        self._add_line('					"G:="			, 128,')
        self._add_line('					"B:="			, 64')
        self._add_line('				]')
        self._add_line('			]')
        self._add_line('		]')
        self._add_line('	])')
        self._add_line('')

        self._signal_line_added = True
        return self

    def add_ground_plane(self):
        """添加地平面 Gnd - 与 tline_1.py 完全一致"""
        if self._ground_added:
            return self

        self._add_line('# ============================================')
        self._add_line('# Ground Plane Gnd')
        self._add_line('# ============================================')
        self._add_line('oEditor.CreateBox(')
        self._add_line('	[')
        self._add_line('		"NAME:BoxParameters",')
        self._add_line('		"XPosition:="		, "-28mm",')
        self._add_line('		"YPosition:="		, "34mm",')
        self._add_line('		"ZPosition:="		, "0mm",')
        self._add_line('		"XSize:="		, "66mm",')
        self._add_line('		"YSize:="		, "-68mm",')
        self._add_line('		"ZSize:="		, "8mm"')
        self._add_line('	],')
        self._add_line('	[')
        self._add_line('		"NAME:Attributes",')
        self._add_line('		"Name:="		, "Box1",')
        self._add_line('		"Flags:="		, "",')
        self._add_line('		"Color:="		, "(143 175 143)",')
        self._add_line('		"Transparency:="	, 0,')
        self._add_line('		"PartCoordinateSystem:=", "Global",')
        self._add_line('		"UDMId:="		, "",')
        self._add_line('		"MaterialValue:="	, "\\"vacuum\\"",')
        self._add_line('		"SurfaceMaterialValue:=", "\\"\\"",')
        self._add_line('		"SolveInside:="		, True,')
        self._add_line('		"ShellElement:="	, False,')
        self._add_line('		"ShellElementThickness:=", "0mm",')
        self._add_line('		"IsMaterialEditable:="	, True,')
        self._add_line('		"UseMaterialAppearance:=", False,')
        self._add_line('		"IsLightweight:="	, False')
        self._add_line('	])')

        # 修改位置/尺寸 - 使用 W0, L0 变量
        self._add_line('oEditor.ChangeProperty(')
        self._add_line('	[')
        self._add_line('		"NAME:AllTabs",')
        self._add_line('		[')
        self._add_line('			"NAME:Geometry3DCmdTab",')
        self._add_line('			[')
        self._add_line('				"NAME:PropServers",')
        self._add_line('				"Box1:CreateBox:1"')
        self._add_line('			],')
        self._add_line('			[')
        self._add_line('				"NAME:ChangedProps",')
        self._add_line('				[')
        self._add_line('					"NAME:Position",')
        self._add_line('					"X:="			, "-W0/2",')
        self._add_line('					"Y:="			, "-L0/2",')
        self._add_line('					"Z:="			, "-H"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:XSize",')
        self._add_line('					"Value:="		, "W0"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:YSize",')
        self._add_line('					"Value:="		, "L0"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:ZSize",')
        self._add_line('					"Value:="		, "-0.035mm"')
        self._add_line('				]')
        self._add_line('			]')
        self._add_line('		]')
        self._add_line('	])')

        # 修改属性 (名称/材料/颜色/透明度)
        self._add_line('oEditor.ChangeProperty(')
        self._add_line('	[')
        self._add_line('		"NAME:AllTabs",')
        self._add_line('		[')
        self._add_line('			"NAME:Geometry3DAttributeTab",')
        self._add_line('			[')
        self._add_line('				"NAME:PropServers",')
        self._add_line('				"Box1"')
        self._add_line('			],')
        self._add_line('			[')
        self._add_line('				"NAME:ChangedProps",')
        self._add_line('				[')
        self._add_line('					"NAME:Name",')
        self._add_line('					"Value:="		, "Gnd"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:Material",')
        self._add_line(f'					"Value:="		, "\\"{self.conductor}\\""')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:Color",')
        self._add_line('					"R:="			, 255,')
        self._add_line('					"G:="			, 128,')
        self._add_line('					"B:="			, 64')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:Transparent",')
        self._add_line('					"Value:="		, 0.8')
        self._add_line('				]')
        self._add_line('			]')
        self._add_line('		]')
        self._add_line('	])')
        self._add_line('')

        self._ground_added = True
        return self

    def add_ports(self):
        """添加端口 P1, P2 - 与 tline_1.py 完全一致"""
        if self._ports_added:
            return self

        imp = self.line["port_impedance"]

        self._add_line('# ============================================')
        self._add_line('# Ports P1, P2')
        self._add_line('# ============================================')
        self._add_line('oEditor.CreateRectangle(')
        self._add_line('	[')
        self._add_line('		"NAME:RectangleParameters",')
        self._add_line('		"IsCovered:="		, True,')
        self._add_line('		"XStart:="		, "4mm",')
        self._add_line('		"YStart:="		, "0mm",')
        self._add_line('		"ZStart:="		, "-23.5mm",')
        self._add_line('		"Width:="		, "1.5mm",')
        self._add_line('		"Height:="		, "2.7mm",')
        self._add_line('		"WhichAxis:="		, "Y"')
        self._add_line('	],')
        self._add_line('	[')
        self._add_line('		"NAME:Attributes",')
        self._add_line('		"Name:="		, "Rectangle1",')
        self._add_line('		"Flags:="		, "",')
        self._add_line('		"Color:="		, "(143 175 143)",')
        self._add_line('		"Transparency:="	, 0,')
        self._add_line('		"PartCoordinateSystem:=", "Global",')
        self._add_line('		"UDMId:="		, "",')
        self._add_line('		"MaterialValue:="	, "\\"vacuum\\"",')
        self._add_line('		"SurfaceMaterialValue:=", "\\"\\"",')
        self._add_line('		"SolveInside:="		, True,')
        self._add_line('		"ShellElement:="	, False,')
        self._add_line('		"ShellElementThickness:=", "0mm",')
        self._add_line('		"IsMaterialEditable:="	, True,')
        self._add_line('		"UseMaterialAppearance:=", False,')
        self._add_line('		"IsLightweight:="	, False')
        self._add_line('	])')

        # 修改 Rectangle 位置/尺寸 (三次修改，与 tline_1.py 一致)
        self._add_line('oEditor.ChangeProperty(')
        self._add_line('	[')
        self._add_line('		"NAME:AllTabs",')
        self._add_line('		[')
        self._add_line('			"NAME:Geometry3DCmdTab",')
        self._add_line('			[')
        self._add_line('				"NAME:PropServers",')
        self._add_line('				"Rectangle1:CreateRectangle:1"')
        self._add_line('			],')
        self._add_line('			[')
        self._add_line('				"NAME:ChangedProps",')
        self._add_line('				[')
        self._add_line('					"NAME:Position",')
        self._add_line('					"X:="			, "-w1/2",')
        self._add_line('					"Y:="			, "0mm",')
        self._add_line('					"Z:="			, "-23.5mm"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:XSize",')
        self._add_line('					"Value:="		, "w1"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:Position",')
        self._add_line('					"X:="			, "-w1/2",')
        self._add_line('					"Y:="			, "0mm",')
        self._add_line('					"Z:="			, "0.035"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:ZSize",')
        self._add_line('					"Value:="		, "-H-0.07mm"')
        self._add_line('				]')
        self._add_line('			]')
        self._add_line('		]')
        self._add_line('	])')

        self._add_line('oEditor.ChangeProperty(')
        self._add_line('	[')
        self._add_line('		"NAME:AllTabs",')
        self._add_line('		[')
        self._add_line('			"NAME:Geometry3DCmdTab",')
        self._add_line('			[')
        self._add_line('				"NAME:PropServers",')
        self._add_line('				"Rectangle1:CreateRectangle:1"')
        self._add_line('			],')
        self._add_line('			[')
        self._add_line('				"NAME:ChangedProps",')
        self._add_line('				[')
        self._add_line('					"NAME:Position",')
        self._add_line('					"X:="			, "-w1/2",')
        self._add_line('					"Y:="			, "0mm",')
        self._add_line('					"Z:="			, "0.035mm"')
        self._add_line('				]')
        self._add_line('			]')
        self._add_line('		]')
        self._add_line('	])')

        self._add_line('oEditor.ChangeProperty(')
        self._add_line('	[')
        self._add_line('		"NAME:AllTabs",')
        self._add_line('		[')
        self._add_line('			"NAME:Geometry3DCmdTab",')
        self._add_line('			[')
        self._add_line('				"NAME:PropServers",')
        self._add_line('				"Rectangle1:CreateRectangle:1"')
        self._add_line('			],')
        self._add_line('			[')
        self._add_line('				"NAME:ChangedProps",')
        self._add_line('				[')
        self._add_line('					"NAME:Position",')
        self._add_line('					"X:="			, "-w1/2",')
        self._add_line('					"Y:="			, "-l1/2",')
        self._add_line('					"Z:="			, "0.035mm"')
        self._add_line('				]')
        self._add_line('			]')
        self._add_line('		]')
        self._add_line('	])')

        # DuplicateMirror 创建 P2
        self._add_line('oEditor.DuplicateMirror(')
        self._add_line('	[')
        self._add_line('		"NAME:Selections",')
        self._add_line('		"Selections:="		, "Rectangle1",')
        self._add_line('		"NewPartsModelFlag:="	, "Model"')
        self._add_line('	],')
        self._add_line('	[')
        self._add_line('		"NAME:DuplicateToMirrorParameters",')
        self._add_line('		"DuplicateMirrorBaseX:=", "0mm",')
        self._add_line('		"DuplicateMirrorBaseY:=", "0mm",')
        self._add_line('		"DuplicateMirrorBaseZ:=", "0mm",')
        self._add_line('		"DuplicateMirrorNormalX:=", "0mm",')
        self._add_line('		"DuplicateMirrorNormalY:=", "1mm",')
        self._add_line('		"DuplicateMirrorNormalZ:=", "0mm"')
        self._add_line('	],')
        self._add_line('	[')
        self._add_line('		"NAME:Options",')
        self._add_line('		"DuplicateAssignments:=", True')
        self._add_line('	],')
        self._add_line('	[')
        self._add_line('		"CreateGroupsForNewObjects:=", False')
        self._add_line('	])')

        # 重命名 P1, P2
        self._add_line('oEditor.ChangeProperty(')
        self._add_line('	[')
        self._add_line('		"NAME:AllTabs",')
        self._add_line('		[')
        self._add_line('			"NAME:Geometry3DAttributeTab",')
        self._add_line('			[')
        self._add_line('				"NAME:PropServers",')
        self._add_line('				"Rectangle1"')
        self._add_line('			],')
        self._add_line('			[')
        self._add_line('				"NAME:ChangedProps",')
        self._add_line('				[')
        self._add_line('					"NAME:Name",')
        self._add_line('					"Value:="		, "P1"')
        self._add_line('				]')
        self._add_line('			]')
        self._add_line('		]')
        self._add_line('	])')

        self._add_line('oEditor.ChangeProperty(')
        self._add_line('	[')
        self._add_line('		"NAME:AllTabs",')
        self._add_line('		[')
        self._add_line('			"NAME:Geometry3DAttributeTab",')
        self._add_line('			[')
        self._add_line('				"NAME:PropServers",')
        self._add_line('				"Rectangle1_1"')
        self._add_line('				],')
        self._add_line('			[')
        self._add_line('				"NAME:ChangedProps",')
        self._add_line('				[')
        self._add_line('					"NAME:Name",')
        self._add_line('					"Value:="		, "P2"')
        self._add_line('				]')
        self._add_line('			]')
        self._add_line('		]')
        self._add_line('	])')
        self._add_line('')

        # 修改 P1 位置/尺寸 (多次修改)
        self._add_line('oEditor.ChangeProperty(')
        self._add_line('	[')
        self._add_line('		"NAME:AllTabs",')
        self._add_line('		[')
        self._add_line('			"NAME:Geometry3DCmdTab",')
        self._add_line('			[')
        self._add_line('					"NAME:PropServers",')
        self._add_line('				"P1:CreateRectangle:1"')
        self._add_line('			],')
        self._add_line('			[')
        self._add_line('				"NAME:ChangedProps",')
        self._add_line('				[')
        self._add_line('					"NAME:Position",')
        self._add_line('					"X:="			, "-w1",')
        self._add_line('					"Y:="			, "-l1/2",')
        self._add_line('					"Z:="			, "0.035mm"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:XSize",')
        self._add_line('					"Value:="		, "2*w1"')
        self._add_line('				]')
        self._add_line('			]')
        self._add_line('		]')
        self._add_line('	])')

        self._add_line('oEditor.ChangeProperty(')
        self._add_line('	[')
        self._add_line('		"NAME:AllTabs",')
        self._add_line('		[')
        self._add_line('			"NAME:Geometry3DCmdTab",')
        self._add_line('			[')
        self._add_line('				"NAME:PropServers",')
        self._add_line('				"P1:CreateRectangle:1"')
        self._add_line('			],')
        self._add_line('			[')
        self._add_line('				"NAME:ChangedProps",')
        self._add_line('				[')
        self._add_line('					"NAME:XSize",')
        self._add_line('					"Value:="		, "4*w1"')
        self._add_line('				]')
        self._add_line('			]')
        self._add_line('		]')
        self._add_line('	])')

        self._add_line('oEditor.ChangeProperty(')
        self._add_line('	[')
        self._add_line('		"NAME:AllTabs",')
        self._add_line('		[')
        self._add_line('			"NAME:Geometry3DCmdTab",')
        self._add_line('			[')
        self._add_line('				"NAME:PropServers",')
        self._add_line('				"P1:CreateRectangle:1"')
        self._add_line('			],')
        self._add_line('			[')
        self._add_line('				"NAME:ChangedProps",')
        self._add_line('				[')
        self._add_line('					"NAME:Position",')
        self._add_line('					"X:="			, "-2*w1",')
        self._add_line('					"Y:="			, "-l1/2",')
        self._add_line('					"Z:="			, "0.035mm"')
        self._add_line('				]')
        self._add_line('			]')
        self._add_line('		]')
        self._add_line('	])')

        self._add_line('oEditor.ChangeProperty(')
        self._add_line('	[')
        self._add_line('		"NAME:AllTabs",')
        self._add_line('		[')
        self._add_line('			"NAME:Geometry3DCmdTab",')
        self._add_line('			[')
        self._add_line('				"NAME:PropServers",')
        self._add_line('				"P1:CreateRectangle:1"')
        self._add_line('			],')
        self._add_line('			[')
        self._add_line('				"NAME:ChangedProps",')
        self._add_line('				[')
        self._add_line('					"NAME:Position",')
        self._add_line('					"X:="			, "-2*w1",')
        self._add_line('					"Y:="			, "-l1/2",')
        self._add_line('					"Z:="			, "0.035mm+4mm"')
        self._add_line('				]')
        self._add_line('			]')
        self._add_line('		]')
        self._add_line('	])')

        self._add_line('oEditor.ChangeProperty(')
        self._add_line('	[')
        self._add_line('		"NAME:AllTabs",')
        self._add_line('		[')
        self._add_line('			"NAME:Geometry3DCmdTab",')
        self._add_line('			[')
        self._add_line('				"NAME:PropServers",')
        self._add_line('				"P1:CreateRectangle:1"')
        self._add_line('			],')
        self._add_line('			[')
        self._add_line('				"NAME:ChangedProps",')
        self._add_line('				[')
        self._add_line('					"NAME:ZSize",')
        self._add_line('					"Value:="		, "-H-0.07mm-4mm"')
        self._add_line('				]')
        self._add_line('			]')
        self._add_line('		]')
        self._add_line('	])')
        self._add_line('')

        # AssignWavePort - P1
        self._add_line('oModule = oDesign.GetModule("BoundarySetup")')
        self._add_line('oModule.AssignWavePort(')
        self._add_line('	[')
        self._add_line('		"NAME:1",')
        self._add_line('		"Objects:="		, ["P1"],')
        self._add_line('		"NumModes:="		, 1,')
        self._add_line('		"UseLineModeAlignment:=", False,')
        self._add_line('		"DoDeembed:="		, False,')
        self._add_line('		"RenormalizeAllTerminals:=", True,')
        self._add_line('		[')
        self._add_line('			"NAME:Modes",')
        self._add_line('			[')
        self._add_line('				"NAME:Mode1",')
        self._add_line('				"ModeNum:="		, 1,')
        self._add_line('				"UseIntLine:="		, True,')
        self._add_line('				[')
        self._add_line('					"NAME:IntLine",')
        self._add_line('					"Start:="		, ["0mm","0mm","-1.635mm"],')
        self._add_line('					"End:="			, ["0mm","0mm","4.035mm"]')
        self._add_line('				],')
        self._add_line('				"AlignmentGroup:="	, 0,')
        self._add_line('				"CharImp:="		, "Zpi",')
        self._add_line(f'				"RenormImp:="		, "{imp}ohm"')
        self._add_line('			]')
        self._add_line('		],')
        self._add_line('		"ShowReporterFilter:="	, False,')
        self._add_line('		"ReporterFilter:="	, [True],')
        self._add_line('		"UseAnalyticAlignment:=", False')
        self._add_line('	])')

        # AssignWavePort - P2
        self._add_line('oModule.AssignWavePort(')
        self._add_line('	[')
        self._add_line('		"NAME:2",')
        self._add_line('		"Objects:="		, ["P2"],')
        self._add_line('		"NumModes:="		, 1,')
        self._add_line('		"UseLineModeAlignment:=", False,')
        self._add_line('		"DoDeembed:="		, False,')
        self._add_line('		"RenormalizeAllTerminals:=", True,')
        self._add_line('		[')
        self._add_line('			"NAME:Modes",')
        self._add_line('			[')
        self._add_line('				"NAME:Mode1",')
        self._add_line('				"ModeNum:="		, 1,')
        self._add_line('				"UseIntLine:="		, True,')
        self._add_line('				[')
        self._add_line('					"NAME:IntLine",')
        self._add_line('					"Start:="		, ["0mm","0mm","-1.6mm"],')
        self._add_line('					"End:="			, ["0mm","0mm","4.035mm"]')
        self._add_line('				],')
        self._add_line('				"AlignmentGroup:="	, 0,')
        self._add_line('				"CharImp:="		, "Zpi",')
        self._add_line(f'				"RenormImp:="		, "{imp}ohm"')
        self._add_line('			]')
        self._add_line('		],')
        self._add_line('		"ShowReporterFilter:="	, False,')
        self._add_line('		"ReporterFilter:="	, [True],')
        self._add_line('		"UseAnalyticAlignment:=", False')
        self._add_line('	])')
        self._add_line('')

        self._ports_added = True
        return self

    def add_air_box_and_radiation(self):
        """添加空气盒和辐射边界 - 与 tline_1.py 完全一致"""
        if self._boundary_added:
            return self

        self._add_line('# ============================================')
        self._add_line('# Air Box')
        self._add_line('# ============================================')
        self._add_line('oEditor.CreateBox(')
        self._add_line('	[')
        self._add_line('		"NAME:BoxParameters",')
        self._add_line('		"XPosition:="		, "-56mm",')
        self._add_line('		"YPosition:="		, "-80mm",')
        self._add_line('		"ZPosition:="		, "0mm",')
        self._add_line('		"XSize:="		, "92mm",')
        self._add_line('		"YSize:="		, "186mm",')
        self._add_line('		"ZSize:="		, "28mm"')
        self._add_line('	],')
        self._add_line('	[')
        self._add_line('		"NAME:Attributes",')
        self._add_line('		"Name:="		, "Box1",')
        self._add_line('		"Flags:="		, "",')
        self._add_line('		"Color:="		, "(143 175 143)",')
        self._add_line('		"Transparency:="	, 0,')
        self._add_line('		"PartCoordinateSystem:=", "Global",')
        self._add_line('		"UDMId:="		, "",')
        self._add_line('		"MaterialValue:="	, "\\"vacuum\\"",')
        self._add_line('		"SurfaceMaterialValue:=", "\\"\\"",')
        self._add_line('		"SolveInside:="		, True,')
        self._add_line('		"ShellElement:="	, False,')
        self._add_line('		"ShellElementThickness:=", "0mm",')
        self._add_line('		"IsMaterialEditable:="	, True,')
        self._add_line('		"UseMaterialAppearance:=", False,')
        self._add_line('		"IsLightweight:="	, False')
        self._add_line('	])')

        # 修改 Air Box 位置/尺寸
        self._add_line('oEditor.ChangeProperty(')
        self._add_line('	[')
        self._add_line('		"NAME:AllTabs",')
        self._add_line('		[')
        self._add_line('			"NAME:Geometry3DCmdTab",')
        self._add_line('			[')
        self._add_line('				"NAME:PropServers",')
        self._add_line('				"Box1:CreateBox:1"')
        self._add_line('			],')
        self._add_line('			[')
        self._add_line('				"NAME:ChangedProps",')
        self._add_line('				[')
        self._add_line('					"NAME:Position",')
        self._add_line('					"X:="			, "-W0/2",')
        self._add_line('					"Y:="			, "-L0/2",')
        self._add_line('					"Z:="			, "15mm"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:XSize",')
        self._add_line('					"Value:="		, "W0"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:YSize",')
        self._add_line('					"Value:="		, "L0"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:ZSize",')
        self._add_line('					"Value:="		, "-30mm"')
        self._add_line('				]')
        self._add_line('			]')
        self._add_line('		]')
        self._add_line('	])')

        # 修改 Air Box 属性 (名称/颜色/透明度)
        self._add_line('oEditor.ChangeProperty(')
        self._add_line('	[')
        self._add_line('		"NAME:AllTabs",')
        self._add_line('		[')
        self._add_line('			"NAME:Geometry3DAttributeTab",')
        self._add_line('			[')
        self._add_line('				"NAME:PropServers",')
        self._add_line('				"Box1"')
        self._add_line('			],')
        self._add_line('			[')
        self._add_line('				"NAME:ChangedProps",')
        self._add_line('				[')
        self._add_line('					"NAME:Name",')
        self._add_line('					"Value:="		, "Air"')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:Color",')
        self._add_line('					"R:="			, 0,')
        self._add_line('					"G:="			, 128,')
        self._add_line('					"B:="			, 255')
        self._add_line('				],')
        self._add_line('				[')
        self._add_line('					"NAME:Transparent",')
        self._add_line('					"Value:="		, 0.8')
        self._add_line('				]')
        self._add_line('			]')
        self._add_line('		]')
        self._add_line('	])')
        self._add_line('')

        # 辐射边界
        self._add_line('# ============================================')
        self._add_line('# Radiation Boundary')
        self._add_line('# ============================================')
        self._add_line('oModule = oDesign.GetModule("BoundarySetup")')
        self._add_line('oModule.AssignRadiation(')
        self._add_line('	[')
        self._add_line('		"NAME:Rad1",')
        self._add_line('		"Objects:="		, ["Air"],')
        self._add_line('		"IsFssReference:="	, False,')
        self._add_line('		"IsForPML:="		, False')
        self._add_line('	])')
        self._add_line('')

        self._boundary_added = True
        return self

    def add_solution_setup(self):
        """添加求解设置 - 与 tline_1.py 一致"""
        if self._setup_added:
            return self

        freq = self.target_freq
        freq_start = max(0.0, freq - 3.0)
        freq_end = freq + 3.0

        self._add_line('# ============================================')
        self._add_line('# Solution Setup')
        self._add_line('# ============================================')
        self._add_line('oModule = oDesign.GetModule("AnalysisSetup")')
        self._add_line('oModule.InsertSetup("HfssDriven",')
        self._add_line('	[')
        self._add_line('		"NAME:Setup1",')
        self._add_line('		"SolveType:="		, "Single",')
        self._add_line(f'		"Frequency:="		, "{self.target_freq}GHz",')
        self._add_line('		"MaxDeltaS:="		, 0.02,')
        self._add_line('		"UseMatrixConv:="	, False,')
        self._add_line('		"MaximumPasses:="	, 8,')
        self._add_line('		"MinimumPasses:="	, 1,')
        self._add_line('		"MinimumConvergedPasses:=", 1,')
        self._add_line('		"PercentRefinement:="	, 30,')
        self._add_line('		"IsEnabled:="		, True,')
        self._add_line('		[')
        self._add_line('			"NAME:MeshLink",')
        self._add_line('			"ImportMesh:="		, False')
        self._add_line('		],')
        self._add_line('		"BasisOrder:="		, 1,')
        self._add_line('		"DoLambdaRefine:="	, True,')
        self._add_line('		"DoMaterialLambda:="	, True,')
        self._add_line('		"SetLambdaTarget:="	, False,')
        self._add_line('		"Target:="		, 0.3333,')
        self._add_line('		"UseMaxTetIncrease:="	, False,')
        self._add_line('		"PortAccuracy:="	, 2,')
        self._add_line('		"UseABCOnPort:="	, False,')
        self._add_line('		"SetPortMinMaxTri:="	, False,')
        self._add_line('		"UseDomains:="		, False,')
        self._add_line('		"UseIterativeSolver:="	, False,')
        self._add_line('		"SaveRadFieldsOnly:="	, False,')
        self._add_line('		"SaveAnyFields:="	, True,')
        self._add_line('		"IESolverType:="	, "Auto",')
        self._add_line('		"LambdaTargetForIESolver:=", 0.15,')
        self._add_line('		"UseDefaultLambdaTgtForIESolver:=", True,')
        self._add_line('		"IE Solver Accuracy:="	, "Balanced"')
        self._add_line('	])')
        self._add_line('')

        # 扫频
        self._add_line('oModule.InsertFrequencySweep("Setup1",')
        self._add_line('	[')
        self._add_line('		"NAME:Sweep",')
        self._add_line('		"IsEnabled:="		, True,')
        self._add_line('		"RangeType:="		, "LinearStep",')
        self._add_line(f'		"RangeStart:="		, "{freq_start:.2f}GHz",')
        self._add_line(f'		"RangeEnd:="		, "{freq_end:.2f}GHz",')
        self._add_line('		"RangeStep:="		, "0.02GHz",')
        self._add_line('		"Type:="		, "Interpolating",')
        self._add_line('		"SaveFields:="		, False,')
        self._add_line('		"SaveRadFields:="	, False,')
        self._add_line('		"InterpTolerance:="	, 0.5,')
        self._add_line('		"InterpMaxSolns:="	, 250,')
        self._add_line('		"InterpMinSolns:="	, 0,')
        self._add_line('		"InterpMinSubranges:="	, 1,')
        self._add_line('		"MinSolvedFreq:="	, "0.01GHz",')
        self._add_line('		"InterpUseS:="		, True,')
        self._add_line('		"InterpUsePortImped:="	, False,')
        self._add_line('		"InterpUsePropConst:="	, True,')
        self._add_line('		"UseDerivativeConvergence:=", False,')
        self._add_line('		"InterpDerivTolerance:=", 0.2,')
        self._add_line('		"UseFullBasis:="	, True,')
        self._add_line('		"EnforcePassivity:="	, True,')
        self._add_line('		"PassivityErrorTolerance:=", 0.0001')
        self._add_line('	])')
        self._add_line('')

        self._setup_added = True
        return self

    def add_reports(self):
        """添加报告"""
        if self._reports_added:
            return self

        self._add_line('# ============================================')
        self._add_line('# Reports')
        self._add_line('# ============================================')
        self._add_line('oModule = oDesign.GetModule("ReportSetup")')
        self._add_line('oModule.CreateReport("S Parameter Plot 1", "Modal Solution Data", "Rectangular Plot", "Setup1 : Sweep",')
        self._add_line('	[')
        self._add_line('		"Domain:="		, "Sweep"')
        self._add_line('	],')
        self._add_line('	[')
        self._add_line('		"Freq:="		, ["All"],')
        self._add_line('		"W0:="			, ["Nominal"],')
        self._add_line('		"L0:="			, ["Nominal"],')
        self._add_line('		"w1:="			, ["Nominal"],')
        self._add_line('		"l1:="			, ["Nominal"],')
        self._add_line('		"H:="			, ["Nominal"]')
        self._add_line('	],')
        self._add_line('	[')
        self._add_line('		"X Component:="		, "Freq",')
        self._add_line('		"Y Component:="		, ["dB(S(1,1))"]')
        self._add_line('	])')
        self._add_line('')

        self._add_line('oModule.CreateReport("TDR Impedance Plot 1", "Modal Solution Data", "Rectangular Plot", "Setup1 : Sweep",')
        self._add_line('	[')
        self._add_line('		"Domain:="		, "Time",')
        self._add_line('		"HoldTime:="		, 1,')
        self._add_line('		"RiseTime:="		, 1E-10,')
        self._add_line('		"StepTime:="		, 2E-11,')
        self._add_line('		"Step:="		, True,')
        self._add_line('		"WindowWidth:="		, 1,')
        self._add_line('		"WindowType:="		, 4,')
        self._add_line('		"KaiserParameter:="	, 1,')
        self._add_line('		"MaximumTime:="		, 2E-09')
        self._add_line('	],')
        self._add_line('	[')
        self._add_line('		"Time:="		, ["All"],')
        self._add_line('		"W0:="			, ["Nominal"],')
        self._add_line('		"L0:="			, ["Nominal"],')
        self._add_line('		"w1:="			, ["Nominal"],')
        self._add_line('		"l1:="			, ["Nominal"],')
        self._add_line('		"H:="			, ["Nominal"]')
        self._add_line('	],')
        self._add_line('	[')
        self._add_line('		"X Component:="		, "Time",')
        self._add_line('		"Y Component:="		, ["mag(TDRZ(1))"]')
        self._add_line('	])')
        self._add_line('')

        self._reports_added = True
        return self

    def add_analyze_and_save(self):
        """添加分析和保存"""
        if self._analyze_added:
            return self

        self._add_line('# ============================================')
        self._add_line('# Save and Analyze')
        self._add_line('# ============================================')
        self._add_line(f'oProject.SaveAs("T:\\\\py_prj\\\\{self.project_name}.aedt", True)')
        self._add_line('oDesign.AnalyzeAll()')
        self._add_line('')

        self._analyze_added = True
        return self

    def build(self) -> str:
        """构建完整脚本"""
        self.add_header()
        self.add_substrate()
        self.add_signal_line()
        self.add_ground_plane()
        self.add_ports()
        self.add_air_box_and_radiation()
        self.add_solution_setup()
        self.add_reports()
        self.add_analyze_and_save()
        return "\n".join(self.script_lines)

    def save_script(self, filepath: str) -> str:
        """保存脚本到文件"""
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        script = self.build()
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(script)
        return script


# ===== 测试 =====
if __name__ == "__main__":
    print("=" * 60)
    print("单端微带线脚本生成器 (基于 tline_1.py)")
    print("=" * 60)

    os.makedirs("T:/TLine_scripts", exist_ok=True)

    builder = TLineScriptBuilder(
        project_name="tlin1",
        target_freq=5.0,
        material="FR4_epoxy",
        conductor="copper"
    )

    builder.set_line(w=2.85, l=100.0)
    builder.save_script("T:/TLine_scripts/single_line.py")

    print("✅ Saved: T:/TLine_scripts/single_line.py")
    print("=" * 60)